mysql:
  host: 127.0.0.1
  username: root
  password: ''
  dbname: 'factions'

factions:
  min-name: 3
  max-name: 16
  max-members: 10
  max-allies: 0
  max-claims-per-fac: 1
  dtr-freeze: 1 # MINUTES dtr freeze
  dtr-regen-time: 5 #SECONDS dtr to regen #dtr-increment
  dtr-increment: 0.1
  dtr-per-player: 1.1
  max-dtr: 6.5

  claim_distance: 50
  amount_per_block: 5.0

  invalid-names:
    - 'Road'
    - 'Spawn'

scoreboard:
  title: "&6&lHCF"
  lines:
    - "&f"
    - "Claim: {%0}"
    - "Spawn Tag: {%1}<display={%2}"
    - "SOTW: {%3} <display=SOTW"
    - "EOTW: {%4} <display=EOTW"
    - "&d"
    - "server.com"
  mod-lines:
    - "Staff Mode"
  koth-lines:
    normal: ""
    special: ""
  custom-timer: "{%0}: {%1}"
