mysql:
  host: 127.0.0.1
  username: root
  password: ''
  dbname: 'factions'

factions:
  min-name: 3
  max-name: 16
  max-members: 10
  max-allies: 0
  max-claims-per-fac: 1
  dtr-freeze: 1 # MINUTES dtr freeze
  dtr-regen-time: 5 #SECONDS dtr to regen #dtr-increment
  dtr-increment: 0.1
  dtr-per-player: 1.1
  max-dtr: 6.5

  claim_distance: 50
  amount_per_block: 5.0

  invalid-names:
    - 'Road'
    - 'Spawn'

scoreboard:
  title: "&6&lValixHCF"
  lines:
    default:
      - '&f'
      - '&c&lCombatTag: &r&c%spawntag-time%<display=%spawntag-enabled%'
      - '%koth-lines%'
      - ''
      - '%mod-lines%'
      - ''
      - '&7valixhcf.net'
    mod-lines:
      - "Staff Mode"
    koth-lines:
      normal: '&9&l%koth-name%: &r&8%koth-time%<display=%koth-enabled%'
    custom-timer:
      - "{%0}: {%1}"